server:
  port: 8080

spring:
  security:
    user:
      name: admin
      password: changeme

  ai:
    openai:
      api-key: ${OPENAI_KEY}
      base-url: "https://api.groq.com/openai"
      chat:
        options:
          model: "llama-3.1-8b-instant"
          temperature: 0.7
    groq:
      api-key: ${GROQAI_KEY}
      base-url: "https://api.groq.com/openai"
      chat:
        options:
          model: "llama-3.1-8b-instant"
          temperature: 0.7
  r2dbc:
    url: r2dbc:h2:mem:///coinsniperdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password:
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

logging:
  level:
    org.springframework.web: DEBUG
    org.springdoc: DEBUG
    org.thymeleaf: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,configprops

coin-sniper:
  supported:
    exchanges:
      - "Binance"
      - "Bybit"
      - "Coinbase"
      - "GateIo"
      - "Kraken"
      - "Kucoin"
      - "MEXC"
      - "OKCoin"
      - "Poloniex"
    stable-coins:
      - "USDT"
      - "USDC"
      - "USD"
  announcement-polling:
    enabled: false
    #interval-seconds: 60
    interval-seconds: 84600 # 1 day (for testing)
  api:
    binance:
      announcement:
        base-url: "https://www.binance.com/bapi/apex/v1/public/apex/cms/article/list/query"
        type: 1
        pageNo: 1
        pageSize: 10
    on-exchange:
      poloniex:
        trade:
          base-url: ""
          api-key: 123
          api-secret: 456
      bybit:
        trade:
          base-url: ""
          api-key: 123
          api-secret: 456

dashboard:
  enabled: true
  maxResults: 50
  defaultExchange: Binance

springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /api-docs



