server:
  port: 8080

spring:
  ai:
    openai:
      api-key: ${OPENAI_KEY}

logging:
  level:
    org.springframework.web: DEBUG
    org.thymeleaf: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,configprops

coin-sniper:
  supported:
    exchanges:
      - "Binance"
      - "Bybit"
      - "Coinbase"
      - "GateIo"
      - "Kraken"
      - "Kucoin"
      - "MEXC"
      - "OKCoin"
      - "Poloniex"
    stable-coins:
      - "USDT"
      - "USDC"
      - "USD"
  announcement-polling:
    enabled: true
    interval-seconds: 30
  api:
    binance:
      announcement:
        base-url: "https://www.binance.com/bapi/apex/v1/public/apex/cms/article/list/query"
        type: 1
        pageNo: 1
        pageSize: 10
    on-exchange:
      poloniex:
        trade:
          base-url: ""
          api-key: 123
          api-secret: 456
      bybit:
        trade:
          base-url: ""
          api-key: 123
          api-secret: 456

dashboard:
  enabled: true
  maxResults: 50
  defaultExchange: Binance

springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /api-docs



